config/routes.rb
Rails.application.routes.draw do
  namespace :study do
    resources :tasks
  end
  namespace :fmis do
    resources :records
  end

  # get '/test/wechat',to: 'wechats#auth_wechat'
  # post '/test/wechat',to: 'wechats#process_request' 

  # devise_for :users
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/index'
  root to: "home#index"
end

app/models/study/task.rb
class Study::Task
  include Mongoid::Document
  field :title, type: String
  field :important, type: Integer
end

app/controllers/study/tasks_controller.rb
class Study::TasksController < ApplicationController
  before_action :set_study_task, only: [:show, :edit, :update, :destroy]

  # GET /study/tasks
  # GET /study/tasks.json
  def index
    @study_tasks = Study::Task.all
  end

  # GET /study/tasks/1
  # GET /study/tasks/1.json
  def show
  end

  # GET /study/tasks/new
  def new
    @study_task = Study::Task.new
  end

  # GET /study/tasks/1/edit
  def edit
  end

  # POST /study/tasks
  # POST /study/tasks.json
  def create
    @study_task = Study::Task.new(study_task_params)

    respond_to do |format|
      if @study_task.save
        format.html { redirect_to @study_task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @study_task }
      else
        format.html { render :new }
        format.json { render json: @study_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study/tasks/1
  # PATCH/PUT /study/tasks/1.json
  def update
    respond_to do |format|
      if @study_task.update(study_task_params)
        format.html { redirect_to @study_task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_task }
      else
        format.html { render :edit }
        format.json { render json: @study_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study/tasks/1
  # DELETE /study/tasks/1.json
  def destroy
    @study_task.destroy
    respond_to do |format|
      format.html { redirect_to study_tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_task
      @study_task = Study::Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_task_params
      params.require(:study_task).permit(:title, :important)
    end
end

app/helpers/study/tasks_helper.rb
module Study::TasksHelper
end

app/views/study/tasks/_form.html.erb
<%= form_with(model: study_task, local: true) do |form| %>
  <% if study_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study_task.errors.count, "error") %> prohibited this study_task from being saved:</h2>

      <ul>
      <% study_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :study_task_title %>
  </div>

  <div class="field">
    <%= form.label :important %>
    <%= form.number_field :important, id: :study_task_important %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/study/tasks/edit.html.erb
<h1>Editing Study Task</h1>

<%= render 'form', study_task: @study_task %>

<%= link_to 'Show', @study_task %> |
<%= link_to 'Back', study_tasks_path %>

app/views/study/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Study Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Important</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_tasks.each do |study_task| %>
      <tr>
        <td><%= study_task.title %></td>
        <td><%= study_task.important %></td>
        <td><%= link_to 'Show', study_task %></td>
        <td><%= link_to 'Edit', edit_study_task_path(study_task) %></td>
        <td><%= link_to 'Destroy', study_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study Task', new_study_task_path %>

app/views/study/tasks/new.html.erb
<h1>New Study Task</h1>

<%= render 'form', study_task: @study_task %>

<%= link_to 'Back', study_tasks_path %>

app/views/study/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @study_task.title %>
</p>

<p>
  <strong>Important:</strong>
  <%= @study_task.important %>
</p>

<%= link_to 'Edit', edit_study_task_path(@study_task) %> |
<%= link_to 'Back', study_tasks_path %>